spring.application.name=explorer
spring.datasource.url=jdbc:postgresql://localhost:5433/berchtesgaden_explorer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgYmVyY2h0ZXNnYWRlbiBleHBsb3Jlcg==
jwt.expiration=86400000